server:
  port: 3333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kot
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # (none, create, create-drop, update, validate)
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

hash:
  cost: 12

jwt:
  access-token-secret: "ThisIsAVeryVerySecretKeyForAccessTokenAndItNeedsToBeLongEnoughForHS512Algorithm"  # 64자 이상
  refresh-token-secret: "ThisIsAnotherVeryVerySecretKeyForRefreshTokenAndItAlsoNeedsToBeLongEnoughForHS512"  # 64자 이상
  access-token-expiration: 86400000  # 24시간
  refresh-token-expiration: 2592000000  # 30일
  
naver:
  api:
    base-url: ${NAVER_BASE_URL}
    api-key-id: ${NAVER_API_KEY_ID}
    api-key: ${NAVER_API_KEY}