server:
  port: 3333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kot
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create # (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

naver:
  api:
    base-url: ${NAVER_BASE_URL}
    api-key-id: ${NAVER_API_KEY_ID}
    api-key: ${NAVER_API_KEY}